### PR TITLE
Enhance deploy scripts to allow custom Docker tag

### PR DESCRIPTION
**Pull request by aednichols**
Example run: 

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/CromIAM/job/cromwell-deploy/801/console
https://gotc-jenkins.dsp-techops.broadinstitute.org/view/CromIAM/job/cromwell-deploy/801/parameters/

Example where Docker tag not set – defaults to env, like before:

https://gotc-jenkins.dsp-techops.broadinstitute.org/view/CromIAM/job/cromwell-deploy/802/console
https://gotc-jenkins.dsp-techops.broadinstitute.org/view/CromIAM/job/cromwell-deploy/802/parameters

### CODE REVIEW

**Review by kshakir — APPROVED** [review]
LGTM

**Review by cjllanwarne — APPROVED** [review]
This all seems correct to me - does it need a concurrent jenkins script update to pass along the new parameter?

**Comment by cjllanwarne** [comment]
Oh, never mind, I just read your comment. But... I don't think your `802` example proves what you think it does, since it was back to using the `dev` branch.

**Comment by aednichols** [comment]
Great catch, I will test correctly

**Comment by aednichols** [comment]
Not so good:
```
dsde-jenkins-deploy.sh: line 60: DOCKERHUB_TAG: unbound variable
```
I think I was hoping the unset variable would be passed through with a null value but it seems that's not the case

**Comment by aednichols** [comment]
@cjllanwarne fixed & thanks again for catching:

`Pulling cromwell (broadinstitute/cromwell:dev)...`

https://gotc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-deploy/814/console

https://gotc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-deploy/814/parameters/

**Comment by cjllanwarne** [comment]
re-👍 but request to please hold off on merging for now, until I complete the caas update...

**Review by cjllanwarne — APPROVED** [review]

**Comment by cjllanwarne** [comment]
@aednichols - CAAS-deploy is complete. you're all set 👍

**Pull request merged**
